name: Test CI/CT/CD Workflows using C

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    # checkout repo
    - uses: actions/checkout@v4
    # build target
    - name: make
      run: make
    # run tests
    - name: test
      run: ./testinput | ./adder | ./checkoutput
    # deploy to build subfolder
    - name: copy target
      run: cp adder build
    - name: deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: docker
        FOLDER: build
        TARGET_DIR: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:

    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
    # checkout repo
    - uses: actions/checkout@v4
    # login to docker hub
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # build docker image
    - name: build docker image
      working-directory: ./build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test-ci-cd-ct .
    - name: push docker image
      working-directory: ./build
      run: docker push ${{ secrets.DOCKER_USERNAME }}/test-ci-cd-ct
